### ISSUE TITLE
mutual information for donut-shaped distribution

### ISSUE THREAD

**Issue by fkloosterman** [robince/gcmi#1]
Thanks for making this method for mutual information estimation available. I have done a quick test in matlab (and python) on a donut-shaped bivariate distribution for which I would expect the mutual information to be non-zero. However the result that gcmi_cc gives is very close to zero.

Is this an expected result, or do I use the functions incorrectly?

Here is the matlab code for the test:

`t=(1:1999)'/200.;`
`s1 = normrnd(1.,0.1,[2000,1]) * sin( 2*pi*t );`
`s2 = normrnd(1.,0.1,[2000,1]) * sin( 2*pi*t - 0.5*pi );`
`gcmi_cc( s1, s2 ) % gives as answer: -3.5968e-04`

**Comment by robince** [comment]
That is an expected result. The GCMI is a lower bound estimate of the mutual information and so is not sensitive to all non-linear effects. In this example the lower bound value is quite far from the true value. GCMI measures only the part of the dependence that can be modelled with a Gaussian copula. In this case if you plot `scatter(ctransform(s1),ctransform(s2))` you will see the symmetry. In this case the best fitting Gaussian copula is the uniform one (r=0, uniform copula on unit square) so the GCMI is measured as 0 (although as you say there is higher true MI between the variables).  In the 1d-1d continuous case in general it is pretty close to a rank correlation and is sensitive to similar effects.

So you lose the full non-linear sensitivity but you gain robustness (particularly for multivariate calculattions) and computational efficiency. 

A revised version of the manuscript explains this in a bit more detail and I will update biorxiv with this shortly.
