### ISSUE TITLE
GCMI in Python gives unexpected results

### ISSUE THREAD

**Issue by DominiqueMakowski** [robince/gcmi#12]
Hi @robince, I just stumbled on your work and it's super interesting! I see we have somewhat related interests in complexity metrics ☺️

We recently implemented quite [a lot](https://neuropsychology.github.io/NeuroKit/functions/complexity.html) of complexity algos in [neurokit](https://github.com/neuropsychology/NeuroKit), and we also have a function to compute Mutual Info using [different types of methods](https://neuropsychology.github.io/NeuroKit/functions/complexity.html#mutual-information). I myself am not an expert at all of this, but I managed to adapt & implement some of these methods so that they are easy to use.

I think it'd be great to add GC MI, and I gave it a quick try by using your code, but unfortunately the results are somewhat unexpected. I computed the MI of two small series under different conditions of noise, using "traditional" approaches and GCMI (MI6 in the plot), but the pattern doesn't look like the others...

![image](https://user-images.githubusercontent.com/8875533/178968670-5c24e828-f898-4629-a93b-4f6d14230026.png)

Am I missing something? Or misunderstanding how to use this function? 

The code to reproduce the fig is in this PR https://github.com/neuropsychology/NeuroKit/pull/677 (& here's the link to the adaptation (mostly streamlining) of your code: https://github.com/neuropsychology/NeuroKit/pull/677/files)

let me know what you think!  cheers

**Comment by robince** [comment]
I think your signal is `y=x**2 + noise`. GCMI won't detect this sort of symmetric effect, it can detect only monotonic effects (it is like a rank correlation). You could try adding in abs(x) as a second dimension of x. 

Also I apprecaite your interest but GCMI is licensed under the GPL so code can't be reused and released under MIT.

**Comment by DominiqueMakowski** [comment]
Thanks for your reply 

> You could try adding in abs(x) as a second dimension of x.

I am not sure what you mean here?

> GCMI is licensed under the GPL

Ah sorry I missed that. Shame, I'll close the PR then!

**Comment by robince** [comment]
```
nk.mutual_information(np.abs(x), y + noise, method="gc")
```
would I think be sensitive to `y=x**2` effect, but requires some sort of prior knowledge (and would lose linear effects). In general if you want to have sensitivity to a symmetric effect you can create a 2d variable  `np.stack([x, np.abs(x-np.median(x))])` and put that as a 2d input for GCMI. There is a cost in terms of sensitivity and sampling variance for going to 2d and it's not very elegant, but just a suggestion :) 

```
nk.mutual_information(np.stack([x, np.abs(x-np.median(x))]), y + noise, method="gc")
```

Sorry about the incompatible license. I have always preferred the GPL for publically funded academic work, but perhaps that view is a bit out of date now!
