### ISSUE TITLE
Pz for gcmi_ccd (Python)

### ISSUE THREAD

**Issue by EtienneCmb** [robince/gcmi#4]
Hi !

Thank you a lot for this nice code. I think there's a mistake for the Python version of the [gcmi_ccd](https://github.com/robince/gcmi/blob/master/python/gcmi.py#L646). Pz should be the sum of idx (and not x.shape) :
```python
Pz[zi] = idx.sum()  # or thsx.shape[-1]
```

**Comment by EtienneCmb** [comment]
And for optimization, the [copnorm](https://github.com/robince/gcmi/blob/master/python/gcmi.py#L33) function uses `scipy.stats.norm.ppf`, which is really slow and is [wrapper](https://github.com/scipy/scipy/blob/v1.2.1/scipy/stats/_continuous_distns.py#L177) of `scipy.special.ndtri`. You could replace `cx = sp.stats.norm.ppf(ctransform(x))` by `cx = sp.special.ndtri(ctransform(x))`. This is almost 10x faster

**Comment by robince** [comment]
Sorry for the delay, thanks very much for finding the bug and the performance improvement. I've made those changes. The Python code has not been very extensively used as I work mostly with Matlab so please let me know if you run into any other issues.
