### ISSUE TITLE
Pypi distribution?

### ISSUE THREAD

**Issue by dizcza** [robince/gcmi#7]
Among the other mutual information estimators, your one looks promising. Are you willing to ship your python implementation to pypi? I'd like to use your package (that hopefully will be updated) instead of just copying the source code.
Thank you.

**Comment by robince** [comment]
Thanks for your interest. I have found Python packaging a bit of a minefield in the past so unless the project grows in complexity beyond a single file with a few functions I think I will stick to github (also so the Python and Matlab implementations can be found together). 

Anyone who wanted to maintain the packaging/pip side would of course be very welcome.
