### ISSUE TITLE
Softmax test overestimated

### ISSUE THREAD

**Issue by dizcza** [robince/gcmi#8]
Dear Robin,

I find your mutual information estimator practically useful for continuos-continuos typical data. But it overestimates the mutual information if the data does not follow Gaussian distribution. Is your estimator supposed to work with Gaussian only distributed data?

I can describe in details my test but it makes sense if your estimator accepts non-gaussian.

Cheers,
Danylo.

**Comment by robince** [comment]
Hi Danylo,

The estimator only is for Gaussian variables (mi_gg function). The combination of the copula normalisation (copnorm function) with the Gaussian MI estimation (mi_gg) (also implemented in gcmi_cc) is an approximate estimator for any data, but it should be a lower bound to the true MI. I.e. it should not overestimate the mutual information, it should underestimate it if there is non-gaussian copula dependence (e.g. asymmetrical effect or long tails). 

More details in the paper: http://onlinelibrary.wiley.com/doi/10.1002/hbm.23471/abstract
